### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by SoumenDass**
To add note that when the game is copied to/run from another folder

### CODE REVIEW

**Comment by tsherif** [comment]
Thanks for the suggestion, @SoumenDass! I'm thinking I'll add a runtime check that the directory exists, rather than a note in the docs, but I'm curious: why was it that you wanted to copy the game elsewhere?

**Comment by SoumenDass** [comment]
Usually I keep my git repos and the location of binaries separate. So after building, I move the binary to the folder where I keep, e.g., games. If you already have support for `make install`, then the copying of the binary + the assets can be done as part of the installation and we do not need to add this note to README.

**Comment by tsherif** [comment]
Ah gotcha, thanks. I'll keep that in mind.

**Comment by tsherif** [comment]
Added checks for the asset directory in 63f5e56 and 53687ff, so I'll close this. Thanks for bringing this use case to my attention!

**Pull request closed without merging**
